
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module r2rv(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	// input 		          		CLOCK2_50,
	// input 		          		CLOCK3_50,
	// inout 		          		CLOCK4_50,

	//////////// SDRAM //////////
	// output		    [12:0]		DRAM_ADDR,
	// output		     [1:0]		DRAM_BA,
	// output		          		DRAM_CAS_N,
	// output		          		DRAM_CKE,
	// output		          		DRAM_CLK,
	// output		          		DRAM_CS_N,
	// inout 		    [15:0]		DRAM_DQ,
	// output		          		DRAM_LDQM,
	// output		          		DRAM_RAS_N,
	// output		          		DRAM_UDQM,
	// output		          		DRAM_WE_N,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	// input 		     [3:0]		KEY,
	input 		          		RESET_N,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// PS2 //////////
	// inout 		          		PS2_CLK,
	// inout 		          		PS2_CLK2,
	// inout 		          		PS2_DAT,
	// inout 		          		PS2_DAT2,

	//////////// SW //////////
	input 		     [9:0]		SW

	//////////// VGA //////////
	// output		     [3:0]		VGA_B,
	// output		     [3:0]		VGA_G,
	// output		          		VGA_HS,
	// output		     [3:0]		VGA_R,
	// output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

  logic we, clk, reset;
  logic [31:0] ra[4], wa, rd[4], wd, outputs[10];
  ldst_mode rm[4], wm;



//=======================================================
//  Structural coding
//=======================================================

  assign LEDR = SW;
  assign reset = !RESET_N;

  clk_divider divide(.clk(CLOCK_50), .divided_clk(clk));
  riscv riscv(.clk, .reset, .we, .ra, .wa, .rm, .wm, .rd, .wd, .outputs);
  mem mem(.clk, .we, .ra, .wa, .rm, .wm, .rd, .wd);
  display display(.clk, .outputs, .SW, .HEX0, .HEX1, .HEX2, .HEX3, .HEX4, .HEX5);



endmodule

